# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

unique_cpp <- function(x) {
    .Call(`_corrRF_unique_cpp`, x)
}

XWX_XWSWX_equicorr_cpp <- function(rho, num_leaves, I, n_i, nodesis, epsilon) {
    .Call(`_corrRF_XWX_XWSWX_equicorr_cpp`, rho, num_leaves, I, n_i, nodesis, epsilon)
}

XWX_XWSWX_XX_equicorr_cpp <- function(rho, num_leaves, I, n_i, nodesis, epsilon) {
    .Call(`_corrRF_XWX_XWSWX_XX_equicorr_cpp`, rho, num_leaves, I, n_i, nodesis, epsilon)
}

XWX_XWY_equicorr_cpp <- function(rho, num_leaves, I, n_i, nodesis, Y) {
    .Call(`_corrRF_XWX_XWY_equicorr_cpp`, rho, num_leaves, I, n_i, nodesis, Y)
}

XWX_XWSWX_XtestX_equicorr_cpp <- function(rho, num_leaves, I, n_i, nodesis, epsilon, N_test, nodesis_test) {
    .Call(`_corrRF_XWX_XWSWX_XtestX_equicorr_cpp`, rho, num_leaves, I, n_i, nodesis, epsilon, N_test, nodesis_test)
}

XWX_XWSWX_ar1_cpp <- function(rho, num_leaves, I, n_i, nodesis, epsilon) {
    .Call(`_corrRF_XWX_XWSWX_ar1_cpp`, rho, num_leaves, I, n_i, nodesis, epsilon)
}

XWX_XWSWX_XX_ar1_cpp <- function(rho, num_leaves, I, n_i, nodesis, epsilon) {
    .Call(`_corrRF_XWX_XWSWX_XX_ar1_cpp`, rho, num_leaves, I, n_i, nodesis, epsilon)
}

XWX_XWY_ar1_cpp <- function(rho, num_leaves, I, n_i, nodesis, Y) {
    .Call(`_corrRF_XWX_XWY_ar1_cpp`, rho, num_leaves, I, n_i, nodesis, Y)
}

XWX_XWSWX_XX_OLD_ar1_cpp <- function(rho, num_leaves, I, n_i, nodesis, epsilon) {
    .Call(`_corrRF_XWX_XWSWX_XX_OLD_ar1_cpp`, rho, num_leaves, I, n_i, nodesis, epsilon)
}

XWX_XWSWX_XtestX_ar1_cpp <- function(rho, num_leaves, I, n_i, nodesis, epsilon, N_test, nodesis_test) {
    .Call(`_corrRF_XWX_XWSWX_XtestX_ar1_cpp`, rho, num_leaves, I, n_i, nodesis, epsilon, N_test, nodesis_test)
}

